// Import type definitions for the data structures.
import { PostData, User, Application, Notification, Feedback } from './types';

// Mock data for notifications for the current user (johnDoe).
export const allNotifications: Notification[] = [
    { id: 1, recipientId: 'johnDoe', type: 'comment', actorId: 'janeSmith', postId: 4, timestamp: '2m ago', read: false },
    { id: 2, recipientId: 'johnDoe', type: 'like', actorId: 'mikeJohnson', postId: 4, timestamp: '15m ago', read: false },
    { id: 3, recipientId: 'johnDoe', type: 'follow', actorId: 'emilyDavis', timestamp: '1h ago', read: false },
    { id: 4, recipientId: 'johnDoe', type: 'team_accept', actorId: 'janeSmith', postId: 5, timestamp: '3h ago', read: true },
    { id: 5, recipientId: 'johnDoe', type: 'team_apply', actorId: 'chrisLee', postId: 4, timestamp: '1d ago', read: true },
    { id: 6, recipientId: 'johnDoe', type: 'like', actorId: 'sarahWilson', postId: 5, timestamp: '2d ago', read: true },
];

// Helper to generate ISO timestamps for mock chat data
const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60 * 1000).toISOString();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();


// Mock data for all posts in the application.
export const allPosts: PostData[] = [
    // --- Posts for the main feed ---
    {
      id: 1, // Unique post ID.
      authorId: 'techInnovations', // ID of the user who created the post.
      timestamp: '8h ago', // Display timestamp.
      idea: { // The core SaaS idea details.
        title: 'A Faster, Simpler UI Framework',
        description: 'I\'ve been thinking a lot about the current state of UI development. It feels like we\'re always choosing between performance, developer experience, and design flexibility. What if we could have all three? I\'m envisioning a new kind of framework that prioritizes simplicity without sacrificing power.',
        problem: 'Building UIs is slow and repetitive, leading to longer development cycles and inconsistent user experiences across projects.',
        solution: 'Our new framework provides a set of reusable, high-performance components and a declarative API that dramatically speeds up UI development and ensures consistency.',
        targetAudience: 'Web developers, front-end teams, and design systems engineers.',
        monetization: 'Open-source core with a paid "Pro" version that includes advanced features, premium support, and enterprise licensing.'
      },
      tags: ['UIFramework', 'DeveloperTools', 'JavaScript', 'WebDev'],
      reactions: { like: 850, buildit: 300, insightful: 50, dislike: 15, confused: 5 }, // Counts for each reaction type.
      currentUserReaction: 'buildit', // The reaction of the current user (johnDoe).
      commentsData: [ // An array of comments on the post.
          { id: 101, authorId: 'chrisLee', content: 'This looks amazing! Can\'t wait to try it out.', likes: 25, liked: false },
          { id: 102, authorId: 'sarahWilson', content: 'Finally! Been waiting for something like this.', likes: 18, liked: false },
          { id: 104, authorId: 'davidBrown', content: 'What\'s the performance like compared to other frameworks?', likes: 7, liked: false },
          { id: 105, authorId: 'lauraTaylor', content: 'The documentation is so clean. Great job team!', likes: 12, liked: false },
      ],
      showJoinTeamButton: true, // Whether the "Join Team" button is active.
      discordLink: 'https://discord.gg/exampleframework',
      applicationQuestions: ['What is your experience with UI frameworks?', 'Why do you want to join this project?'], // Questions for applicants.
      teamApplicants: [{ // Users who have applied to the team.
        applicantId: 'emilyDavis',
        answers: [
          { question: 'What is your experience with UI frameworks?', answer: 'I have 5 years of experience with React and Vue.' },
          { question: 'Why do you want to join this project?', answer: 'I am passionate about developer experience and this project aligns perfectly with my interests.' }
        ]
      }],
      teamMembers: ['mikeJohnson', 'johnDoe'], // User IDs of current team members.
      chat: [ // Mock chat history for the team.
        { id: 1, senderId: 'techInnovations', text: 'Welcome to the team, everyone! Let\'s get started on the component architecture.', timestamp: minutesAgo(65) },
        { id: 2, senderId: 'mikeJohnson', text: 'Excited to be here! I have some initial thoughts on the state management. I can put together a quick proposal.', timestamp: minutesAgo(63) },
        { id: 3, senderId: 'johnDoe', text: 'Sounds good, Mike. I\'ll start mocking up the basic button and input components.', timestamp: minutesAgo(62) },
        { id: 4, senderId: 'techInnovations', text: 'Perfect. Let\'s sync up tomorrow morning to review.', timestamp: minutesAgo(48), reactions: { '👍': ['mikeJohnson', 'johnDoe'] } },
      ]
    },
    {
      id: 2,
      authorId: 'sarahMiller',
      timestamp: 'Yesterday at 9:14 PM',
      idea: {
        title: "TrailFinder AI: Your Personal Hiking Guide",
        problem: "Finding the perfect hiking trail is difficult. Existing apps have cluttered UIs and unreliable, outdated information.",
        solution: "An AI-powered app that suggests personalized hiking trails based on your fitness level, desired scenery, and real-time weather conditions.",
        targetAudience: "Hikers, outdoor enthusiasts, and families looking for their next adventure.",
        monetization: "Freemium model with a subscription for advanced features like offline maps, AI itinerary planning, and safety alerts."
      },
      tags: ['AI', 'MobileApp', 'Outdoors', 'TravelTech'],
      reactions: { like: 150, love: 100, fire: 6 },
      currentUserReaction: 'like',
      commentsData: [],
      showJoinTeamButton: true,
      discordLink: 'https://discord.gg/examplehiking',
      applicationQuestions: ["Why are you interested in outdoor tech projects?"],
      teamApplicants: [],
      teamMembers: [],
    },
     {
      id: 3,
      authorId: 'designWeekly',
      timestamp: '2 days ago',
      idea: {
        title: "NeumorphKit: Easy Neumorphism for UI Designers",
        problem: "Creating neumorphic designs is time-consuming and difficult to implement consistently in code, often leading to inaccessible interfaces.",
        solution: "A Figma plugin and component library that allows designers and developers to generate beautiful, accessible neumorphic components with one click.",
        targetAudience: "UI/UX Designers and Frontend Developers who use Figma.",
        monetization: "One-time purchase for the plugin/library with lifetime updates."
      },
      tags: ['Design', 'UIUX', 'Figma', 'Neumorphism'],
      reactions: { like: 700, love: 191, dislike: 120, dontbuildit: 45 },
      currentUserReaction: null, // No reaction from the current user.
      commentsData: [
          { id: 301, authorId: 'mikeJohnson', content: 'I think it\'s a bit overused now, but can be effective when done right.', likes: 42, liked: false },
      ],
      showJoinTeamButton: false, // This is just an idea, not a team project.
      teamApplicants: [],
      teamMembers: [],
    },
    // --- Posts for John Doe's profile ---
    {
      id: 4,
      authorId: 'johnDoe',
      timestamp: '4h ago',
      idea: {
        title: "DevSpace: Virtual Workspace Optimizer",
        description: 'Just had a flash of inspiration for a new SaaS idea. I call it DevSpace. The core concept is to completely abstract away the local development environment. No more "it works on my machine" issues!',
        problem: "Managing development environments across multiple machines is a hassle, leading to inconsistencies and hours of lost productivity.",
        solution: "A SaaS platform that provides cloud-based, containerized development environments accessible from any browser. One-click setup for any stack.",
        targetAudience: "Software developers, freelancers, and remote development teams.",
        monetization: "Subscription-based pricing per user, with tiers based on usage hours and collaborative features."
      },
      tags: ['SaaS', 'DevOps', 'Cloud', 'DeveloperTools'],
      reactions: { like: 150, fire: 20, insightful: 18 },
      currentUserReaction: null, // The author doesn't react to their own post in this data set.
      commentsData: [
        { id: 401, authorId: 'janeSmith', content: 'Looks great John! Very clean setup.', likes: 15, liked: false },
        { id: 402, authorId: 'mikeJohnson', content: 'Love the dual monitors!', likes: 8, liked: false },
        { 
          id: 404, 
          authorId: 'chrisLee', 
          content: 'What keyboard is that?',
          likes: 4,
          liked: false,
          replies: [ // Example of a nested reply.
            { id: 406, authorId: 'johnDoe', content: 'It\'s the Keychron K2! Highly recommend it.', likes: 2, liked: false }
          ]
        },
        { id: 405, authorId: 'sarahWilson', content: 'Inspiring!', likes: 11, liked: false },
      ],
      showJoinTeamButton: true,
      discordLink: 'https://discord.gg/exampledevspace',
      applicationQuestions: ['What is your backend development experience?', 'Provide a link to your GitHub profile.'],
      teamApplicants: [{
        applicantId: 'chrisLee',
        answers: [
          { question: 'What is your backend development experience?', answer: 'Extensive experience with Node.js, Express, and databases like PostgreSQL and MongoDB.' },
          { question: 'Provide a link to your GitHub profile.', answer: 'https://github.com/chrislee' }
        ]
      }],
      teamMembers: [],
    },
    {
      id: 5,
      authorId: 'johnDoe',
      timestamp: 'Yesterday at 9:14 PM',
      idea: {
        title: "SnapRoute: Photo-driven Travel Planning",
        description: 'Has this ever happened to you? You see a stunning travel photo on social media and think, "I want to go there!" But then you have to spend hours researching the location, figuring out flights, and finding a place to stay. It\'s a huge pain point that I think technology can solve.',
        problem: "People see amazing travel photos online but have no easy way to plan a trip to recreate that experience.",
        solution: "An app where you can upload a photo, and our AI will identify the location and generate a full travel itinerary, including flights, hotels, and photo spots.",
        targetAudience: "Travelers, photographers, and social media influencers.",
        monetization: "Commission on affiliate bookings (flights, hotels) and a premium subscription for advanced AI planning features."
      },
      tags: ['AI', 'TravelTech', 'MobileApp', 'SaaS'],
      reactions: { like: 200, love: 56 },
      currentUserReaction: null,
      commentsData: [
         { id: 503, authorId: 'emilyDavis', content: 'Wow, where was this taken?', likes: 22, liked: false },
      ],
      showJoinTeamButton: true,
      discordLink: 'https://discord.gg/examplesnaproute',
      applicationQuestions: ["What's your experience with travel tech or AI?"],
      teamApplicants: [],
      teamMembers: ['janeSmith'],
      chat: [
        { id: 1, senderId: 'johnDoe', text: 'Hey Jane, thanks for joining the team for SnapRoute!', timestamp: daysAgo(2) },
        { id: 2, senderId: 'janeSmith', text: 'No problem! I love this idea. I think we should start with the image recognition module.', timestamp: daysAgo(2) },
        { id: 3, senderId: 'johnDoe', text: 'Agreed. I was looking into a few third-party APIs we could use to speed up development.', timestamp: daysAgo(1) },
        { id: 4, senderId: 'janeSmith', text: 'Let me know what you find!', timestamp: daysAgo(1), reactions: { '👍': ['johnDoe'] } },
      ],
    },
     {
      id: 6,
      authorId: 'johnDoe',
      timestamp: '2 days ago',
      idea: {
        title: "CritiqueConnect: Get Real-time Design Feedback",
        problem: "Getting high-quality, actionable feedback on design mockups is difficult and often happens too late in the process, causing costly revisions.",
        solution: "A collaborative platform where designers can upload their work and get instant feedback from a community of peers and mentors through annotations and video comments.",
        targetAudience: "UI/UX designers, product designers, and students.",
        monetization: "Freemium model with a Pro plan for private projects and advanced team features."
      },
      tags: ['Design', 'UIUX', 'Collaboration', 'SaaS'],
      reactions: { insightful: 500, like: 391 },
      currentUserReaction: null,
      commentsData: [],
      showJoinTeamButton: false,
      teamApplicants: [],
      teamMembers: [],
    },
    // --- More posts for a richer feed ---
    {
      id: 7,
      authorId: 'janeSmith',
      timestamp: '3 days ago',
      idea: {
        title: "CogniScribe: AI-Powered Meeting Summarizer",
        problem: "Professionals waste hours taking notes in meetings and even more time trying to decipher them later. Key action items get lost.",
        solution: "A SaaS tool that integrates with Zoom/Teams/Meet, records audio, and provides an accurate, searchable transcript with AI-generated summaries and identified action items.",
        targetAudience: "Project managers, consultants, remote teams, and executives.",
        monetization: "Tiered subscription based on number of transcription hours per month."
      },
      tags: ['AI', 'Productivity', 'SaaS', 'FutureOfWork'],
      reactions: { insightful: 120, like: 345, buildit: 98 },
      currentUserReaction: 'insightful',
      commentsData: [],
      showJoinTeamButton: true,
      applicationQuestions: ["What's your experience with Natural Language Processing (NLP)?", "How would you market a tool like this?"],
      teamApplicants: [],
      teamMembers: [],
    },
    {
      id: 8,
      authorId: 'mikeJohnson',
      timestamp: '3 days ago',
      idea: {
        title: "SubScribe: Hassle-Free Subscription Management for D2C Brands",
        problem: "Direct-to-consumer brands struggle to manage recurring payments, customer churn, and subscription logic, often relying on clunky, expensive solutions.",
        solution: "A simple, developer-friendly API and dashboard to manage subscriptions, automate billing, and provide analytics to reduce churn.",
        targetAudience: "E-commerce businesses, D2C brands, and startups.",
        monetization: "Percentage fee on transaction volume + a flat monthly fee for premium features."
      },
      tags: ['FinTech', 'Ecommerce', 'SaaS', 'API'],
      reactions: { like: 99, fire: 12 },
      currentUserReaction: null,
      commentsData: [],
      showJoinTeamButton: false,
    },
    {
      id: 9,
      authorId: 'aiFrontiers',
      timestamp: '4 days ago',
      idea: {
        title: "Aequitas AI: Ethical AI Auditing Platform",
        problem: "As AI models become more prevalent, ensuring they are fair, unbiased, and transparent is a major challenge for organizations, exposing them to legal and reputational risks.",
        solution: "A platform that analyzes machine learning models for bias across various demographics, explains their decision-making processes, and generates compliance reports.",
        targetAudience: "Data science teams, compliance officers, and large enterprises in regulated industries (finance, healthcare).",
        monetization: "Enterprise license based on the number of models audited."
      },
      tags: ['AI', 'Ethics', 'MachineLearning', 'Enterprise'],
      reactions: { insightful: 550, like: 800 },
      currentUserReaction: 'like',
      commentsData: [
        { id: 901, authorId: 'johnDoe', content: 'This is critically important. A much-needed tool in the industry.', likes: 35, liked: true },
        { id: 902, authorId: 'techInnovations', content: 'We\'ve been looking for a solution like this. How do you handle model explainability for complex deep learning architectures?', likes: 28, liked: false }
      ],
      showJoinTeamButton: true,
      applicationQuestions: ["What is your background in data ethics or AI fairness?"],
      teamApplicants: [],
      teamMembers: [],
    },
    {
      id: 10,
      authorId: 'emilyDavis',
      timestamp: '4 days ago',
      idea: {
        title: "LingoLeap: Gamified Language Learning for Professionals",
        problem: "Learning a new language for business is often tedious and disconnected from real-world professional scenarios.",
        solution: "A mobile app that uses gamification, AI-powered conversation partners, and industry-specific vocabulary modules (e.g., 'Spanish for Finance') to make learning practical and engaging.",
        targetAudience: "Business professionals, multinational corporations, and frequent travelers.",
        monetization: "Freemium with a premium subscription for advanced lessons and features."
      },
      tags: ['EdTech', 'AI', 'MobileApp', 'Gamification'],
      reactions: { love: 250, buildit: 80, like: 400 },
      currentUserReaction: null,
      commentsData: [],
      showJoinTeamButton: true,
      applicationQuestions: ["Which language would you focus on first and why?", "Do you have experience in mobile app development?"],
      teamApplicants: [],
      teamMembers: [],
    },
    {
        id: 11,
        authorId: 'chrisLee',
        timestamp: '5 days ago',
        idea: {
          title: "API-Forge: No-Code API Builder",
          problem: "Small businesses and entrepreneurs often need custom APIs to connect their services but lack the technical expertise or resources to build them from scratch.",
          solution: "A visual, drag-and-drop interface for building, testing, and deploying robust REST APIs without writing a single line of code. Connect to databases, third-party services, and more.",
          targetAudience: "Startups, indie hackers, and small business owners.",
          monetization: "Tiered monthly subscription based on API calls and features."
        },
        tags: ['NoCode', 'API', 'SaaS', 'DeveloperTools'],
        reactions: { like: 280, buildit: 150 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 12,
        authorId: 'quantumComputingDaily',
        timestamp: '5 days ago',
        idea: {
          title: "QuantumGuard: Post-Quantum Encryption as a Service",
          problem: "The advent of quantum computing threatens to break current encryption standards, leaving sensitive data vulnerable in the near future.",
          solution: "An API-first service that provides quantum-resistant cryptographic algorithms, allowing developers to easily upgrade their applications' security for the quantum era.",
          targetAudience: "Financial institutions, governments, and enterprise software companies.",
          monetization: "Usage-based pricing (per API call) and enterprise licensing."
        },
        tags: ['QuantumComputing', 'Security', 'Crypto', 'API'],
        reactions: { insightful: 700, like: 1200 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 13,
        authorId: 'davidBrown',
        timestamp: '6 days ago',
        idea: {
          title: "NutriPlan: Personalized Meal Planning for Health Goals",
          problem: "People struggle to maintain healthy diets because meal planning is time-consuming and generic plans don't account for personal preferences, allergies, or health goals.",
          solution: "A web and mobile app that uses AI to generate weekly meal plans and shopping lists tailored to an individual's dietary needs, fitness goals, and taste preferences.",
          targetAudience: "Fitness enthusiasts, individuals with dietary restrictions, and busy professionals.",
          monetization: "Monthly or annual subscription."
        },
        tags: ['HealthTech', 'AI', 'Wellness', 'MobileApp'],
        reactions: { like: 180, love: 90 },
        currentUserReaction: 'like',
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Do you have a background in nutrition or dietetics?", "What is your favorite healthy recipe?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 14,
        authorId: 'lauraTaylor',
        timestamp: '6 days ago',
        idea: {
          title: "SceneCraft: Collaborative Storyboarding for Filmmakers",
          problem: "Filmmaking teams, especially remote ones, find it hard to collaborate on storyboards. Traditional methods are static and version control is a nightmare.",
          solution: "A real-time, collaborative web-based tool where directors, artists, and writers can create and comment on storyboards together, with features for version history and animatics.",
          targetAudience: "Independent filmmakers, animation studios, and advertising agencies.",
          monetization: "Subscription model based on the number of projects and users."
        },
        tags: ['CreativeTech', 'Collaboration', 'SaaS', 'Filmmaking'],
        reactions: { insightful: 60, buildit: 45, like: 150 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 15,
        authorId: 'techInnovations',
        timestamp: '1 week ago',
        idea: {
          title: "IoT-Sense: Predictive Maintenance for Industrial Machines",
          problem: "Unexpected equipment failure in manufacturing plants causes costly downtime and production delays.",
          solution: "A platform that connects to IoT sensors on industrial machinery, using machine learning to predict potential failures before they happen and scheduling maintenance proactively.",
          targetAudience: "Manufacturing companies, factory managers, and maintenance teams.",
          monetization: "Subscription fee per machine monitored."
        },
        tags: ['IoT', 'MachineLearning', 'Manufacturing', 'SaaS'],
        reactions: { like: 650, insightful: 220 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What is your experience with IoT or machine learning?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 16,
        authorId: 'jamesMartinez',
        timestamp: '1 week ago',
        idea: {
          title: "NeighborHub: Hyper-Local Community Marketplace",
          problem: "It's hard to discover and support local small businesses, home-based services, or neighbors selling goods. Existing platforms are too broad.",
          solution: "A mobile-first platform focused on connecting people within a specific neighborhood or community to buy, sell, and trade goods and services.",
          targetAudience: "Local communities, small businesses, and individuals looking to sell homemade goods.",
          monetization: "Optional listing fees for businesses and small transaction fees."
        },
        tags: ['Marketplace', 'Local', 'Community', 'MobileApp'],
        reactions: { like: 88, love: 40 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 17,
        authorId: 'jessicaAnderson',
        timestamp: '8 days ago',
        idea: {
          title: "MindWell: AI Mental Wellness Companion for Teams",
          problem: "Employee burnout and mental health are major concerns for companies, but existing solutions are often impersonal and underutilized.",
          solution: "A Slack/Teams-integrated chatbot that provides personalized mental wellness exercises, mindfulness reminders, and confidential access to resources, with anonymized analytics for HR.",
          targetAudience: "HR departments, corporate wellness programs, and remote-first companies.",
          monetization: "Per-employee, per-month subscription."
        },
        tags: ['HRTech', 'AI', 'MentalHealth', 'Wellness', 'SaaS'],
        reactions: { love: 300, insightful: 150, like: 450 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Why are you passionate about mental health in the workplace?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 18,
        authorId: 'designWeekly',
        timestamp: '8 days ago',
        idea: {
          title: "FontPair: A Font Pairing Generator using Machine Learning",
          problem: "Designers and developers spend too much time trying to find the perfect font combination for their projects.",
          solution: "A tool that uses a trained ML model to suggest visually harmonious font pairings based on a user's initial font selection and desired mood (e.g., 'elegant', 'modern', 'playful').",
          targetAudience: "Web designers, graphic designers, and developers.",
          monetization: "Free tool with a pro subscription for more advanced features like custom font uploads and saving palettes."
        },
        tags: ['Design', 'MachineLearning', 'AI', 'DeveloperTools'],
        reactions: { like: 1100, love: 400 },
        currentUserReaction: 'love',
        commentsData: [
            { id: 1801, authorId: 'lauraTaylor', content: 'This would save me so much time!', likes: 25, liked: false }
        ],
        showJoinTeamButton: false,
    },
    {
        id: 19,
        authorId: 'danielThomas',
        timestamp: '9 days ago',
        idea: {
          title: "RestoStock: Smart Inventory Management for Restaurants",
          problem: "Restaurants lose significant money due to food spoilage and inefficient inventory tracking.",
          solution: "A tablet-based app that uses sales data from POS systems to predict ingredient needs, streamline ordering from suppliers, and minimize waste.",
          targetAudience: "Restaurant owners, chefs, and kitchen managers.",
          monetization: "Monthly subscription based on the size of the restaurant."
        },
        tags: ['FoodTech', 'SaaS', 'AI', 'MobileApp'],
        reactions: { like: 210, insightful: 80 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Do you have experience in the restaurant or hospitality industry?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 20,
        authorId: 'sarahMiller',
        timestamp: '10 days ago',
        idea: {
          title: "ContentStream: AI-Powered Social Media Content Scheduler",
          problem: "Social media managers struggle to consistently create and post engaging content across multiple platforms.",
          solution: "A tool that not only schedules posts but also uses AI to suggest content ideas, generate captions based on an image or link, and determine the optimal time to post for maximum engagement.",
          targetAudience: "Social media managers, marketing agencies, and small business owners.",
          monetization: "Tiered monthly subscription based on the number of connected social accounts."
        },
        tags: ['MarTech', 'AI', 'SocialMedia', 'SaaS'],
        reactions: { like: 950, buildit: 300 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Which social media platform do you know best?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 21,
        authorId: 'johnDoe',
        timestamp: '11 days ago',
        idea: {
            title: "ConnectSphere: Personal CRM for Networking",
            description: "Thinking about another problem I have personally. I meet a lot of great people at conferences and online, but I'm terrible at keeping track of who they are, where we met, and what we talked about. A simple personal CRM could solve this.",
            problem: "Professionals struggle to manage their personal network effectively. Contact info is scattered, and important context is forgotten over time.",
            solution: "A lightweight CRM focused on personal relationships. It would allow you to add contacts, tag them, add notes from conversations, and set reminders to follow up.",
            targetAudience: "Salespeople, freelancers, consultants, and anyone who relies on a strong professional network.",
            monetization: "Freemium model. Free for up to 50 contacts, with a pro subscription for unlimited contacts and integrations."
        },
        tags: ['CRM', 'Productivity', 'Networking', 'SaaS'],
        reactions: { like: 350, insightful: 90 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 22,
        authorId: 'janeSmith',
        timestamp: '12 days ago',
        idea: {
            title: "VerdeTrace: Carbon Footprint Tracker for Businesses",
            problem: "Companies want to become more sustainable but lack easy-to-use tools to measure, manage, and report their carbon footprint.",
            solution: "A SaaS platform that integrates with a company's accounting and operations software to automatically calculate their carbon emissions and suggest actionable reduction strategies.",
            targetAudience: "Small to medium-sized businesses, sustainability officers, and B-Corps.",
            monetization: "Monthly subscription based on company size."
        },
        tags: ['ClimateTech', 'Sustainability', 'SaaS', 'Enterprise'],
        reactions: { like: 400, insightful: 250 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What is your experience with sustainability or environmental science?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 23,
        authorId: 'mikeJohnson',
        timestamp: '2 weeks ago',
        idea: {
            title: "AccessiFit: Inclusive Fitness App",
            problem: "The fitness app market is saturated, but very few apps are designed for people with disabilities, limited mobility, or chronic conditions.",
            solution: "A fitness app featuring customizable workout plans, adaptive exercises, and tutorials led by trainers with disabilities, promoting inclusivity in wellness.",
            targetAudience: "People with disabilities, physical therapy patients, and senior citizens.",
            monetization: "Subscription-based with a portion of profits donated to disability advocacy groups."
        },
        tags: ['HealthTech', 'Accessibility', 'Fitness', 'MobileApp'],
        reactions: { love: 800, like: 1200 },
        currentUserReaction: null,
        commentsData: [
            { id: 2301, authorId: 'jessicaAnderson', content: 'This is an incredibly important and underserved market. Wonderful idea!', likes: 50, liked: false }
        ],
        showJoinTeamButton: true,
        applicationQuestions: ["Why is inclusive design important to you?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 24,
        authorId: 'aiFrontiers',
        timestamp: '2 weeks ago',
        idea: {
            title: "LexiGen: Generative AI for Legal Document Drafting",
            problem: "Lawyers spend countless hours drafting routine legal documents, a process that is both time-consuming and prone to human error.",
            solution: "A secure, AI-powered platform trained on legal corpora that can generate first drafts of contracts, motions, and other legal documents based on simple prompts, which can then be reviewed by a lawyer.",
            targetAudience: "Law firms, in-house legal departments, and solo practitioners.",
            monetization: "Subscription fee per user, with add-ons for specific legal specializations."
        },
        tags: ['LegalTech', 'AI', 'GenerativeAI', 'SaaS'],
        reactions: { insightful: 450, like: 600 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 25,
        authorId: 'emilyDavis',
        timestamp: '15 days ago',
        idea: {
            title: "EngageSphere: Virtual Event Platform Reimagined",
            problem: "Most virtual event platforms are glorified video streams with a chat box. They lack the networking and engagement features that make in-person events valuable.",
            solution: "A platform with features like virtual breakout rooms with collaborative whiteboards, AI-powered matchmaking for networking, and gamified exhibitor booths.",
            targetAudience: "Event organizers, corporate marketers, and universities.",
            monetization: "Per-event pricing based on the number of attendees and features used."
        },
        tags: ['EventTech', 'SaaS', 'AI', 'FutureOfWork'],
        reactions: { buildit: 200, like: 550 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What is the most engaging virtual event you've attended and why?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 26,
        authorId: 'techInnovations',
        timestamp: '16 days ago',
        idea: {
            title: "InternalWorks: Low-Code Platform for Internal Tools",
            problem: "Engineering teams are often pulled away from core product work to build and maintain simple internal tools (admin panels, dashboards, etc.).",
            solution: "A low-code platform that allows developers to quickly build and deploy secure, custom internal applications using a library of pre-built UI components and data connectors.",
            targetAudience: "Software engineering teams, IT departments, and operations managers.",
            monetization: "Per-user/per-month subscription."
        },
        tags: ['LowCode', 'DeveloperTools', 'SaaS', 'InternalTools'],
        reactions: { like: 900, buildit: 450, insightful: 150 },
        currentUserReaction: 'buildit',
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Have you built internal tools before? What was your biggest pain point?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 27,
        authorId: 'lauraTaylor',
        timestamp: '16 days ago',
        idea: {
            title: "EstateFlow: Digital Inheritance Planning",
            problem: "Managing digital assets (crypto, social media accounts, cloud storage) after someone passes away is a chaotic and stressful process for family members.",
            solution: "A secure digital vault where users can store credentials and instructions for their digital assets, with a trusted executor system for seamless transfer upon death.",
            targetAudience: "Tech-savvy individuals, cryptocurrency holders, and estate planners.",
            monetization: "Annual subscription for the secure vault service."
        },
        tags: ['FinTech', 'Security', 'Web3', 'SaaS'],
        reactions: { insightful: 320, like: 180 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 28,
        authorId: 'davidBrown',
        timestamp: '17 days ago',
        idea: {
            title: "CodeTutor AI: Personalized Coding Mentor",
            problem: "Beginner programmers often get stuck on simple errors and need immediate, personalized feedback that forums or documentation can't provide.",
            solution: "An AI-powered VS Code extension that provides real-time, contextual feedback on a user's code, explains complex concepts, and suggests improvements like a personal tutor.",
            targetAudience: "Students, coding bootcamp attendees, and junior developers.",
            monetization: "Freemium model with a pro subscription for advanced language support and features."
        },
        tags: ['EdTech', 'AI', 'DeveloperTools', 'VSCode'],
        reactions: { like: 1500, buildit: 600, fire: 100 },
        currentUserReaction: 'like',
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What programming language are you most proficient in?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 29,
        authorId: 'sarahMiller',
        timestamp: '17 days ago',
        idea: {
            title: "GigSafe: Escrow and Contract Management for Freelancers",
            problem: "Freelancers often face scope creep and late payments, creating financial instability and client disputes.",
            solution: "A platform that combines simple contract templates with a secure milestone-based escrow system, ensuring freelancers get paid on time for completed work.",
            targetAudience: "Freelance developers, designers, writers, and consultants.",
            monetization: "A small percentage fee (e.g., 3-5%) on each transaction."
        },
        tags: ['FinTech', 'Freelance', 'FutureOfWork', 'SaaS'],
        reactions: { like: 750, insightful: 120 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 30,
        authorId: 'quantumComputingDaily',
        timestamp: '18 days ago',
        idea: {
            title: "SimuVerse: Quantum Circuit Simulator in the Cloud",
            problem: "Access to quantum computers is limited and expensive, hindering research and development in the field.",
            solution: "A cloud-based platform that provides an intuitive interface for building and simulating quantum circuits on powerful classical hardware, with an option to queue jobs for real quantum hardware.",
            targetAudience: "Researchers, students, and companies exploring quantum computing.",
            monetization: "Pay-as-you-go based on simulation time and resources used."
        },
        tags: ['QuantumComputing', 'DeepTech', 'Cloud', 'SaaS'],
        reactions: { insightful: 900, like: 1100 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 31,
        authorId: 'johnDoe',
        timestamp: '18 days ago',
        idea: {
            title: "LocalizeAI: Automated App Localization",
            problem: "Translating an application into multiple languages is a manual, error-prone, and continuous process for development teams.",
            solution: "A service that integrates with GitHub repos, automatically detects new text strings, uses AI for high-quality initial translation, and provides an interface for human reviewers to approve changes.",
            targetAudience: "SaaS companies, mobile app developers, and global businesses.",
            monetization: "Subscription based on the number of strings translated and repositories linked."
        },
        tags: ['AI', 'DeveloperTools', 'SaaS', 'Localization'],
        reactions: { like: 450, buildit: 180 },
        currentUserReaction: 'buildit',
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Do you speak multiple languages?", "What's your experience with i18n?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 32,
        authorId: 'designWeekly',
        timestamp: '19 days ago',
        idea: {
            title: "BrandGuard: AI-Powered Brand Consistency Checker",
            problem: "In large organizations, marketing materials, presentations, and social media posts often deviate from brand guidelines, diluting the brand's identity.",
            solution: "An AI tool that scans documents, images, and websites to ensure they adhere to a company's brand guidelines (logos, colors, fonts, and tone of voice).",
            targetAudience: "Marketing teams, brand managers, and large enterprises.",
            monetization: "Monthly subscription based on the number of users and assets scanned."
        },
        tags: ['MarTech', 'AI', 'Design', 'SaaS'],
        reactions: { like: 820, insightful: 210 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 33,
        authorId: 'chrisLee',
        timestamp: '20 days ago',
        idea: {
            title: "HealthSync API: Unified Health Data Connector",
            problem: "Health data is fragmented across wearables (Fitbit, Apple Watch), apps, and electronic health records, making it impossible for users to get a holistic view.",
            solution: "A single, secure API that allows developers to build apps that access a user's consolidated health data (with their permission) from hundreds of sources.",
            targetAudience: "Health tech startups, insurance companies, and wellness app developers.",
            monetization: "Freemium API access, with paid tiers for higher usage and enterprise features."
        },
        tags: ['HealthTech', 'API', 'Data', 'SaaS'],
        reactions: { like: 680, buildit: 250 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What's your experience with health data or APIs like HealthKit?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 34,
        authorId: 'jessicaAnderson',
        timestamp: '3 weeks ago',
        idea: {
            title: "ParentPlan: Co-Parenting Organization App",
            problem: "Co-parenting is challenging, with communication breakdowns over schedules, expenses, and important documents.",
            solution: "A dedicated app for co-parents featuring a shared calendar, expense tracking and reimbursement, a secure document vault, and a non-confrontational communication tool.",
            targetAudience: "Divorced or separated parents.",
            monetization: "Monthly subscription with a free trial."
        },
        tags: ['MobileApp', 'FamilyTech', 'Productivity'],
        reactions: { love: 400, like: 250 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 35,
        authorId: 'techInnovations',
        timestamp: '3 weeks ago',
        idea: {
            title: "InfraCost: Cloud Cost Anomaly Detection",
            problem: "Unexpected spikes in cloud bills (AWS, GCP, Azure) can cripple a startup's finances, and they are often discovered too late.",
            solution: "A service that monitors a company's cloud spending, uses machine learning to detect cost anomalies in real-time, and sends alerts with details on the source of the spike.",
            targetAudience: "DevOps engineers, CTOs, and startups.",
            monetization: "Subscription based on a percentage of the cloud bill."
        },
        tags: ['FinOps', 'Cloud', 'DevOps', 'SaaS', 'AI'],
        reactions: { insightful: 450, like: 700 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 36,
        authorId: 'emilyDavis',
        timestamp: '3 weeks ago',
        idea: {
            title: "ReadRecap: AI Summarizer for Articles & Papers",
            problem: "People have endless reading lists of articles, newsletters, and academic papers they never have time to get through.",
            solution: "A browser extension and mobile app that uses AI to generate concise, bullet-point summaries of any online article or uploaded PDF.",
            targetAudience: "Students, researchers, and lifelong learners.",
            monetization: "Freemium model, with a pro subscription for unlimited summaries and advanced features."
        },
        tags: ['AI', 'Productivity', 'EdTech', 'BrowserExtension'],
        reactions: { like: 1200, buildit: 400 },
        currentUserReaction: 'like',
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 37,
        authorId: 'janeSmith',
        timestamp: '3 weeks ago',
        idea: {
            title: "EventConnect: Smart Networking for Conference Attendees",
            problem: "Networking at large conferences is inefficient and based on serendipity. It's hard to find the right people to talk to.",
            solution: "A mobile app for specific events that uses attendees' profiles and interests to suggest high-value connections and facilitate meeting scheduling.",
            targetAudience: "Conference organizers and attendees.",
            monetization: "Sold as a service to conference organizers."
        },
        tags: ['EventTech', 'Networking', 'AI', 'MobileApp'],
        reactions: { like: 350, insightful: 90 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 38,
        authorId: 'mikeJohnson',
        timestamp: '4 weeks ago',
        idea: {
            title: "AuthZero-for-Hardware: IoT Device Authentication",
            problem: "Securing and managing authentication for thousands of IoT devices in the field is a massive security and logistical challenge.",
            solution: "A centralized, API-driven service that provides secure, scalable, and easy-to-implement authentication and authorization for IoT devices.",
            targetAudience: "IoT hardware manufacturers and enterprise IoT solution providers.",
            monetization: "Subscription based on the number of active devices."
        },
        tags: ['IoT', 'Security', 'API', 'SaaS'],
        reactions: { insightful: 500, like: 600 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What's your experience with IoT security?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 39,
        authorId: 'aiFrontiers',
        timestamp: '4 weeks ago',
        idea: {
            title: "SynthVoice: Ethical AI Voice Generation for Creators",
            problem: "Content creators need high-quality voiceovers but hiring voice actors is expensive. Existing text-to-speech is robotic, and deepfake voice cloning has ethical issues.",
            solution: "An AI voice platform where creators can use ethically-licensed, realistic AI voices, or train a custom AI voice with a verified voice actor from our marketplace.",
            targetAudience: "YouTubers, podcasters, and e-learning course creators.",
            monetization: "Subscription for access to voice library and pay-per-use for custom voice generation."
        },
        tags: ['AI', 'GenerativeAI', 'CreatorEconomy', 'SaaS'],
        reactions: { like: 950, buildit: 300, fire: 50 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 40,
        authorId: 'danielThomas',
        timestamp: '1 month ago',
        idea: {
            title: "ChurnPredict: Proactive Customer Churn Prediction",
            problem: "By the time a SaaS company realizes a customer is at risk of churning, it's often too late to save them.",
            solution: "A tool that connects to a company's CRM and product analytics, using machine learning to generate a 'churn risk score' for each customer and highlighting at-risk accounts.",
            targetAudience: "SaaS companies, customer success teams, and subscription businesses.",
            monetization: "Monthly subscription based on the number of customers tracked."
        },
        tags: ['SaaS', 'AI', 'Analytics', 'CRM'],
        reactions: { insightful: 600, like: 850 },
        currentUserReaction: 'insightful',
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 41,
        authorId: 'sarahWilson',
        timestamp: '1 month ago',
        idea: {
            title: "CycleTrack: Urban Commute Planner for Cyclists",
            problem: "Google Maps is for cars. It often suggests dangerous, high-traffic routes for cyclists.",
            solution: "A navigation app designed for urban cyclists that prioritizes routes with dedicated bike lanes, lower traffic, and better safety, using crowdsourced data.",
            targetAudience: "City cyclists, bike commuters, and delivery riders.",
            monetization: "Freemium with a pro subscription for features like elevation profiles and weather integration."
        },
        tags: ['MobileApp', 'Maps', 'Community', 'Sustainability'],
        reactions: { like: 400, love: 150 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Are you an avid cyclist?", "What's the biggest problem with cycling in your city?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 42,
        authorId: 'jamesMartinez',
        timestamp: '1 month ago',
        idea: {
            title: "PortfolioPal: Automated Portfolio Website Builder for Creatives",
            problem: "Designers, artists, and photographers need a portfolio website but often lack the time or technical skills to build and maintain one.",
            solution: "A service that automatically pulls a creative's latest work from platforms like Dribbble, Behance, and Instagram to create and update a beautiful, customizable portfolio website.",
            targetAudience: "Freelance creatives, designers, and artists.",
            monetization: "Monthly subscription for hosting and an automated sync service."
        },
        tags: ['CreatorEconomy', 'Portfolio', 'Automation', 'SaaS'],
        reactions: { like: 550, buildit: 180 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 43,
        authorId: 'johnDoe',
        timestamp: '1 month ago',
        idea: {
            title: "SupportFlow: AI-Powered Triage for Support Tickets",
            problem: "Support teams get overwhelmed by the volume of incoming tickets, and manually categorizing and routing them is a major bottleneck.",
            solution: "An AI tool that integrates with Zendesk or Intercom, automatically analyzes incoming tickets, categorizes them, and routes them to the correct agent or department.",
            targetAudience: "Customer support teams and SaaS companies.",
            monetization: "Subscription based on the number of tickets processed."
        },
        tags: ['AI', 'CustomerSupport', 'SaaS', 'Automation'],
        reactions: { like: 620, insightful: 250 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 44,
        authorId: 'designWeekly',
        timestamp: '1 month ago',
        idea: {
            title: "A11yScan: Automated Accessibility Testing",
            problem: "Web accessibility is a legal and ethical requirement, but manual testing is slow and requires specialized expertise.",
            solution: "A CI/CD-integrated tool that automatically scans web applications for WCAG compliance issues, provides detailed reports, and suggests code fixes.",
            targetAudience: "Frontend developers, QA testers, and large enterprises.",
            monetization: "Subscription based on the number of pages scanned or projects linked."
        },
        tags: ['Accessibility', 'DeveloperTools', 'QA', 'SaaS'],
        reactions: { insightful: 700, like: 900, buildit: 300 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 45,
        authorId: 'lauraTaylor',
        timestamp: '5 weeks ago',
        idea: {
            title: "NomadNet: High-Speed Internet Finder for Digital Nomads",
            problem: "Digital nomads and remote workers constantly struggle to find cafes and co-working spaces with reliable, fast Wi-Fi.",
            solution: "A crowdsourced mobile app that lets users test and share Wi-Fi speeds from locations around the world, creating a reliable map of the best places to work.",
            targetAudience: "Digital nomads, remote workers, and frequent travelers.",
            monetization: "Freemium with a pro subscription for advanced search filters and offline maps."
        },
        tags: ['RemoteWork', 'TravelTech', 'Community', 'MobileApp'],
        reactions: { like: 880, buildit: 220 },
        currentUserReaction: 'like',
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 46,
        authorId: 'davidBrown',
        timestamp: '5 weeks ago',
        idea: {
            title: "LearnSphere: Skill-sharing Marketplace",
            problem: "Many people have valuable skills they could teach, but lack an easy platform to market their knowledge and manage bookings.",
            solution: "A marketplace that allows experts to list online classes or one-on-one sessions, handling scheduling, payments, and video conferencing.",
            targetAudience: "Professionals, hobbyists, and anyone looking to learn or teach a new skill.",
            monetization: "A commission fee on all bookings."
        },
        tags: ['EdTech', 'Marketplace', 'CreatorEconomy'],
        reactions: { like: 720, insightful: 180 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What skill would you teach on LearnSphere?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 47,
        authorId: 'chrisLee',
        timestamp: '5 weeks ago',
        idea: {
            title: "PodCastle: AI-Powered Podcast Editing",
            problem: "Editing podcasts is a slow, manual process. Removing filler words, awkward pauses, and background noise can take hours.",
            solution: "A web-based audio editor that uses AI to automatically detect and remove filler words ('um', 'ah'), shorten silences, and enhance voice quality with one click.",
            targetAudience: "Podcasters, content creators, and marketing teams.",
            monetization: "Subscription based on hours of audio processed per month."
        },
        tags: ['AI', 'CreatorEconomy', 'Podcasting', 'SaaS'],
        reactions: { like: 1300, buildit: 500, fire: 80 },
        currentUserReaction: 'buildit',
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Are you a podcaster? Share a link to your show!", "What's your audio editing experience?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 48,
        authorId: 'sarahMiller',
        timestamp: '6 weeks ago',
        idea: {
            title: "PrivacyGuard: Personal Data Removal Service",
            problem: "Our personal information is scattered across countless data broker websites without our consent, leading to spam, scams, and privacy invasions.",
            solution: "An automated service that scans the web for a user's exposed personal information and sends removal requests to data brokers on their behalf.",
            targetAudience: "Privacy-conscious individuals.",
            monetization: "Annual subscription for continuous monitoring and removal."
        },
        tags: ['Privacy', 'Security', 'SaaS', 'Automation'],
        reactions: { insightful: 900, like: 1100 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 49,
        authorId: 'techInnovations',
        timestamp: '6 weeks ago',
        idea: {
            title: "DocuSign for Web3: On-Chain Agreement Protocol",
            problem: "Signing and verifying agreements in a decentralized way is complex and lacks a standardized, user-friendly interface.",
            solution: "A platform that allows users to create, sign, and store agreements as smart contracts on a blockchain, providing a verifiable and tamper-proof record.",
            targetAudience: "DAOs, Web3 projects, and freelance developers in the crypto space.",
            monetization: "A small gas fee-like transaction cost for executing agreements."
        },
        tags: ['Web3', 'Blockchain', 'DAO', 'LegalTech'],
        reactions: { like: 550, insightful: 300 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["What's your experience with smart contract development?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 50,
        authorId: 'janeSmith',
        timestamp: '7 weeks ago',
        idea: {
            title: "HabitForge: Social Accountability for Habits",
            problem: "Sticking to new habits is hard to do alone. Lack of accountability is a primary reason people fail.",
            solution: "A mobile app where users can form small, private groups to track shared habits (e.g., 'Workout Daily', 'Read 10 pages'). Progress is shared with the group to create positive peer pressure.",
            targetAudience: "Individuals focused on self-improvement.",
            monetization: "Freemium model with a pro subscription for advanced tracking and group features."
        },
        tags: ['MobileApp', 'Productivity', 'Community', 'Wellness'],
        reactions: { like: 800, love: 250 },
        currentUserReaction: 'like',
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 51,
        authorId: 'quantumComputingDaily',
        timestamp: '7 weeks ago',
        idea: {
            title: "Molecule.AI: Quantum Simulation for Drug Discovery",
            problem: "Simulating molecular interactions for drug discovery is computationally intensive for classical computers, slowing down pharmaceutical research.",
            solution: "A cloud platform that leverages quantum-inspired algorithms and (eventually) real quantum hardware to simulate molecular dynamics, accelerating the identification of new drug candidates.",
            targetAudience: "Pharmaceutical companies, biotech startups, and research universities.",
            monetization: "Pay-per-simulation or enterprise-level subscriptions for dedicated computational resources."
        },
        tags: ['QuantumComputing', 'AI', 'BioTech', 'DeepTech'],
        reactions: { insightful: 1500, like: 2200 },
        currentUserReaction: 'insightful',
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 52,
        authorId: 'mikeJohnson',
        timestamp: '8 weeks ago',
        idea: {
            title: "GameDev Assets Marketplace (with better terms)",
            problem: "Major game asset stores take a significant cut from creators' earnings (30% or more).",
            solution: "A new marketplace for 3D models, scripts, and audio for game developers that offers a much more creator-friendly revenue split (e.g., 90/10).",
            targetAudience: "Indie game developers and asset creators.",
            monetization: "10% commission on all sales."
        },
        tags: ['GameDev', 'Marketplace', 'CreatorEconomy'],
        reactions: { like: 950, buildit: 400 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Are you a game developer or a 3D artist? Share your portfolio!", "What game engine do you use most?"],
        teamApplicants: [],
        teamMembers: [],
    },
    {
        id: 53,
        authorId: 'lauraTaylor',
        timestamp: '8 weeks ago',
        idea: {
            title: "ElderConnect: Simplified Tech Support for Seniors",
            problem: "Seniors often struggle with modern technology and need patient, on-demand support, but their family members are not always available.",
            solution: "A subscription service providing unlimited, friendly tech support for seniors via phone or video call with agents trained specifically to assist them.",
            targetAudience: "Senior citizens and their families.",
            monetization: "Monthly or annual subscription plans."
        },
        tags: ['Services', 'Accessibility', 'FamilyTech'],
        reactions: { love: 1200, insightful: 300, like: 900 },
        currentUserReaction: null,
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 54,
        authorId: 'jessicaAnderson',
        timestamp: '9 weeks ago',
        idea: {
            title: "LegalBrief AI: Case Law Summarizer",
            problem: "Law students and paralegals spend an inordinate amount of time reading and summarizing dense legal precedents.",
            solution: "An AI tool that can take a legal case document as input and generate a concise summary, including the key facts, legal issues, and the court's holding.",
            targetAudience: "Law students, paralegals, and junior associates.",
            monetization: "Subscription service, with potential university partnerships."
        },
        tags: ['LegalTech', 'AI', 'EdTech', 'SaaS'],
        reactions: { insightful: 850, like: 1100 },
        currentUserReaction: 'like',
        commentsData: [],
        showJoinTeamButton: false,
    },
    {
        id: 55,
        authorId: 'designWeekly',
        timestamp: '9 weeks ago',
        idea: {
            title: "UserFlow.io: Animated User Flow Diagrams",
            problem: "Static user flow diagrams in Figma or Sketch fail to capture the dynamic nature and micro-interactions of a real application.",
            solution: "A web-based tool that allows designers to create user flow diagrams where the connections are animated, showing screen transitions and micro-interactions, making presentations to stakeholders more effective.",
            targetAudience: "UI/UX designers, product managers, and design agencies.",
            monetization: "Freemium model with a pro version for private projects and team collaboration."
        },
        tags: ['Design', 'UIUX', 'Productivity', 'SaaS'],
        reactions: { like: 1400, buildit: 600, insightful: 200 },
        currentUserReaction: 'buildit',
        commentsData: [],
        showJoinTeamButton: true,
        applicationQuestions: ["Share a link to your design portfolio.", "What's your biggest frustration with current design tools?"],
        teamApplicants: [],
        teamMembers: [],
    }
];

// Mock data for user feedback.
export const allFeedback: Feedback[] = [
    { id: 1, userId: 'janeSmith', text: 'The search bar on the home feed sometimes disappears when scrolling up too fast. It\'s a bit jarring.', type: 'bug', status: 'new', timestamp: daysAgo(1) },
    { id: 2, userId: 'mikeJohnson', text: 'It would be amazing if we could have polls in posts to gauge interest in different features for a SaaS idea.', type: 'feature', status: 'inProgress', timestamp: daysAgo(2) },
    { id: 3, userId: 'chrisLee', text: 'Love the platform! The dark mode is easy on the eyes. Keep up the great work.', type: 'general', status: 'resolved', timestamp: daysAgo(2) },
    { id: 4, userId: 'emilyDavis', text: 'I\'m getting a notification badge, but when I open the dropdown, there\'s nothing new there. The badge doesn\'t clear.', type: 'bug', status: 'new', timestamp: daysAgo(3) },
    { id: 5, userId: 'davidBrown', text: 'Can we get markdown support in the post descriptions? Would be great for formatting code snippets and lists.', type: 'feature', status: 'new', timestamp: daysAgo(4) },
    { id: 6, userId: 'sarahWilson', text: 'The "Who to Follow" suggestions are surprisingly good!', type: 'general', status: 'resolved', timestamp: daysAgo(5) },
    { id: 7, userId: 'lauraTaylor', text: 'On mobile, when I click a tag, it takes me to search, but the keyboard doesn\'t pop up automatically. Minor UX friction.', type: 'bug', status: 'inProgress', timestamp: daysAgo(6) },
    { id: 8, userId: 'sarahMiller', text: 'I would love to be able to categorize my saved posts into different collections, like "Marketing Ideas" or "DevTools".', type: 'feature', status: 'new', timestamp: daysAgo(7) },
    { id: 9, userId: 'jamesMartinez', text: 'The app feels really fast and responsive. Whatever UI framework you are using is working wonders.', type: 'general', status: 'resolved', timestamp: daysAgo(8) },
    { id: 10, userId: 'jessicaAnderson', text: 'The analytics in the admin dashboard are fantastic, but could we get an option to export the data to CSV?', type: 'feature', status: 'inProgress', timestamp: daysAgo(9) },
    { id: 11, userId: 'danielThomas', text: 'Sometimes when I submit a comment, it appears twice in the UI until I refresh the page.', type: 'bug', status: 'new', timestamp: daysAgo(10) },
];


// Mock data for all users in the application.
export const users: { [key: string]: User } = {
  johnDoe: {
    id: 'johnDoe',
    name: 'John Doe',
    avatarUrl: 'https://i.pravatar.cc/150?u=johnDoe',
    bio: 'Founder & CEO at DevWorks | Building the future of software development, one line of code at a time. 🚀',
    location: 'San Francisco, CA',
    education: 'Studied Computer Science at Stanford University',
    relationshipStatus: 'Married',
    postsCount: 12,
    followersCount: 1258,
    followingCount: 15,
    skills: ['React', 'TypeScript', 'Node.js', 'UI/UX Design', 'SaaS Architecture', 'Product Management'],
    portfolio: [
        { title: 'Personal Website', url: 'https://johndoe.dev' },
        { title: 'DevSpace Project', url: 'https://github.com/johndoe/devspace' },
        { title: 'Design Concepts', url: 'https://dribbble.com/johndoe' },
    ],
    following: ['janeSmith', 'techInnovations', 'aiFrontiers', 'designWeekly', 'mikeJohnson', 'chrisLee', 'sarahWilson', 'davidBrown', 'lauraTaylor', 'emilyDavis', 'sarahMiller', 'quantumComputingDaily', 'jamesMartinez', 'jessicaAnderson', 'danielThomas'],
  },
  janeSmith: {
    id: 'janeSmith',
    name: 'Jane Smith',
    avatarUrl: 'https://i.pravatar.cc/150?u=janeSmith',
    bio: 'Product Manager at Innovate Inc. Passionate about user-centric design and building products people love.',
    location: 'New York, NY',
    education: 'MBA from Harvard Business School',
    followersCount: 890,
    followingCount: 200,
    skills: ['Product Management', 'Agile Methodologies', 'User Research', 'Market Analysis'],
    portfolio: [
        { title: 'LinkedIn Profile', url: 'https://linkedin.com/in/janesmith' }
    ],
    following: ['johnDoe', 'techInnovations'],
  },
  mikeJohnson: {
    id: 'mikeJohnson',
    name: 'Mike Johnson',
    avatarUrl: 'https://i.pravatar.cc/150?u=mikeJohnson',
    bio: 'Full-stack developer with a love for clean code and scalable architecture. JavaScript enthusiast.',
    location: 'Austin, TX',
    education: 'B.S. in Software Engineering from MIT',
    followersCount: 1500,
    followingCount: 350,
    skills: ['JavaScript', 'React', 'Vue.js', 'GraphQL', 'Docker', 'AWS'],
    portfolio: [
        { title: 'GitHub Profile', url: 'https://github.com/mikejohnson' }
    ],
    following: ['johnDoe', 'techInnovations'],
  },
  emilyDavis: {
    id: 'emilyDavis',
    name: 'Emily Davis',
    avatarUrl: 'https://i.pravatar.cc/150?u=emilyDavis',
    bio: 'Marketing Director at GrowthCo. Helping SaaS companies scale their user base through data-driven strategies.',
    followersCount: 750,
    followingCount: 180,
    following: [],
  },
  chrisLee: {
    id: 'chrisLee',
    name: 'Chris Lee',
    avatarUrl: 'https://i.pravatar.cc/150?u=chrisLee',
    bio: 'Indie Hacker & No-Code Advocate. Building in public. Follow my journey!',
    followersCount: 2500,
    followingCount: 500,
    following: [],
  },
  sarahWilson: {
    id: 'sarahWilson',
    name: 'Sarah Wilson',
    avatarUrl: 'https://i.pravatar.cc/150?u=sarahWilson',
    bio: 'Venture Capitalist at Valley Ventures. Investing in the next generation of B2B SaaS.',
    followersCount: 10500,
    followingCount: 800,
    following: [],
  },
  davidBrown: {
    id: 'davidBrown',
    name: 'David Brown',
    avatarUrl: 'https://i.pravatar.cc/150?u=davidBrown',
    bio: 'Cybersecurity expert and consultant. Keeping the web safe.',
    followersCount: 980,
    followingCount: 210,
    following: [],
  },
  lauraTaylor: {
    id: 'lauraTaylor',
    name: 'Laura Taylor',
    avatarUrl: 'https://i.pravatar.cc/150?u=lauraTaylor',
    bio: 'UX Researcher focused on creating intuitive and accessible products.',
    followersCount: 620,
    followingCount: 150,
    following: [],
  },
  sarahMiller: {
    id: 'sarahMiller',
    name: 'Sarah Miller',
    avatarUrl: 'https://i.pravatar.cc/150?u=sarahMiller',
    bio: 'Content strategist and copywriter for tech startups.',
    followersCount: 450,
    followingCount: 130,
    following: [],
  },
  jamesMartinez: {
    id: 'jamesMartinez',
    name: 'James Martinez',
    avatarUrl: 'https://i.pravatar.cc/150?u=jamesMartinez',
    bio: 'Mobile developer (iOS & Android). Building beautiful and performant apps.',
    followersCount: 1100,
    followingCount: 300,
    following: [],
  },
  jessicaAnderson: {
    id: 'jessicaAnderson',
    name: 'Jessica Anderson',
    avatarUrl: 'https://i.pravatar.cc/150?u=jessicaAnderson',
    bio: 'Data Scientist. Turning data into insights and products.',
    followersCount: 1800,
    followingCount: 400,
    following: [],
  },
  danielThomas: {
    id: 'danielThomas',
    name: 'Daniel Thomas',
    avatarUrl: 'https://i.pravatar.cc/150?u=danielThomas',
    bio: 'DevOps engineer passionate about automation and cloud infrastructure.',
    followersCount: 850,
    followingCount: 220,
    following: [],
  },
  techInnovations: {
    id: 'techInnovations',
    name: 'Tech Innovations',
    avatarUrl: 'https://i.pravatar.cc/150?u=techInnovations',
    bio: 'A collective of builders and dreamers exploring the future of technology.',
    followersCount: 50000,
    followingCount: 10,
    following: [],
  },
  designWeekly: {
    id: 'designWeekly',
    name: 'Design Weekly',
    avatarUrl: 'https://i.pravatar.cc/150?u=designWeekly',
    bio: 'Curating the best of design and UI/UX every week.',
    followersCount: 120000,
    followingCount: 5,
    following: [],
  },
  aiFrontiers: {
    id: 'aiFrontiers',
    name: 'AI Frontiers',
    avatarUrl: 'https://i.pravatar.cc/150?u=aiFrontiers',
    bio: 'Exploring the cutting edge of Artificial Intelligence and Machine Learning.',
    followersCount: 95000,
    followingCount: 25,
    following: [],
  },
  quantumComputingDaily: {
    id: 'quantumComputingDaily',
    name: 'Quantum Computing Daily',
    avatarUrl: 'https://i.pravatar.cc/150?u=quantumComputingDaily',
    bio: 'Your daily dose of quantum computing news and breakthroughs.',
    followersCount: 75000,
    followingCount: 15,
    following: [],
  },
  personaWeb3: {
    id: 'personaWeb3',
    name: 'Alex "Web3" Chen',
    avatarUrl: 'https://i.pravatar.cc/150?u=personaWeb3',
    bio: 'You are an expert in decentralized technologies. Your tone is forward-thinking, slightly cypherpunk, and highly technical. You post about DAOs, DeFi, blockchain infrastructure, and on-chain governance. You believe decentralization is the future of the internet.',
    followersCount: 12500,
    followingCount: 50,
    isPersona: true,
  },
  personaMarketer: {
    id: 'personaMarketer',
    name: 'Brenda Growth',
    avatarUrl: 'https://i.pravatar.cc/150?u=personaMarketer',
    bio: 'You are a data-driven marketing guru. Your tone is energetic, professional, and full of actionable advice. You post about MarTech, growth hacking, SEO, content marketing, and customer acquisition strategies. You live and breathe metrics and funnels.',
    followersCount: 22000,
    followingCount: 450,
    isPersona: true,
  },
  personaDesigner: {
    id: 'personaDesigner',
    name: 'Carlos "UX" Ruiz',
    avatarUrl: 'https://i.pravatar.cc/150?u=personaDesigner',
    bio: 'You are a passionate UI/UX designer with a keen eye for aesthetics and usability. Your tone is empathetic, creative, and focused on the user. You post about design systems, accessibility, user research, Figma plugins, and beautiful interfaces. You believe great design is invisible.',
    followersCount: 18000,
    followingCount: 300,
    isPersona: true,
  },
};